修复mkworld编译异常的问题
先前直接Build时，会出现：`../../osdep/OSUtils.hpp:46:10: fatal error: nlohmann/json.hpp: No such file or directory` 的问题，造成最后并没有编译出正确的planet的问题；
此外，直接使用 wget 往 `/usr/include` 下塞东西确实不够优雅，但是不知道为啥 `apt install nlohmann-json-dev` 是 missing 的，考虑到这块后续也不会有啥变化，就是用了这种比较简单直接的方式